# Form implementation generated from reading ui file 'style.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        mainWindow.resize(1920, 1080)
        mainWindow.setMinimumSize(QtCore.QSize(1920, 1080))
        mainWindow.setMaximumSize(QtCore.QSize(1920, 1080))
        mainWindow.setStyleSheet("")
        mainWindow.setWindowFilePath("")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setStyleSheet("#{\n"
"height:100%;\n"
"width:100%\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 1922, 1090))
        self.layoutWidget.setObjectName("layoutWidget")
        self.main = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.main.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.main.setContentsMargins(0, 0, 0, 0)
        self.main.setSpacing(0)
        self.main.setObjectName("main")
        self.widget = QtWidgets.QWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(1920, 60))
        self.widget.setSizeIncrement(QtCore.QSize(1920, 60))
        self.widget.setBaseSize(QtCore.QSize(1920, 60))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.widget.setFont(font)
        self.widget.setStyleSheet("#widget{background-color:#42a5f5 }")
        self.widget.setObjectName("widget")
        self.pic = QtWidgets.QLabel(self.widget)
        self.pic.setGeometry(QtCore.QRect(260, 0, 60, 60))
        self.pic.setText("")
        self.pic.setPixmap(QtGui.QPixmap("data/shark.ico"))
        self.pic.setScaledContents(True)
        self.pic.setObjectName("pic")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(360, 10, 931, 41))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        font.setKerning(True)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("")
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(0, 0, 220, 60))
        self.label.setStyleSheet("#label{background-color:#0077c2}")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pc_close = QtWidgets.QPushButton(self.widget)
        self.pc_close.setEnabled(True)
        self.pc_close.setGeometry(QtCore.QRect(1770, 10, 131, 41))
        self.pc_close.setAcceptDrops(False)
        self.pc_close.setAutoFillBackground(False)
        self.pc_close.setStyleSheet("/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:18pt;\n"
"    /*字体颜色为白色*/    \n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(255, 80, 83);\n"
"    /*边框圆角半径为22像素*/ \n"
"    border-radius:16px;\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(254, 0, 0);\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(254, 0, 0);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        self.pc_close.setObjectName("pc_close")
        self.label_time = QtWidgets.QLabel(self.widget)
        self.label_time.setGeometry(QtCore.QRect(1400, 10, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        self.label_time.setFont(font)
        self.label_time.setObjectName("label_time")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(1060, 32, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(208, 208, 208)")
        self.label_2.setObjectName("label_2")
        self.label_4.raise_()
        self.label.raise_()
        self.pic.raise_()
        self.pc_close.raise_()
        self.label_time.raise_()
        self.label_2.raise_()
        self.main.addWidget(self.widget)
        self.widget1 = QtWidgets.QWidget(self.layoutWidget)
        self.widget1.setObjectName("widget1")
        self.tabWidget = QtWidgets.QTabWidget(self.widget1)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(220, 0, 1700, 1020))
        self.tabWidget.setMinimumSize(QtCore.QSize(1700, 1020))
        self.tabWidget.setStyleSheet("#tab,#tab_2,#tab_5{\n"
"    background-color: rgb(240, 245, 250);\n"
"}\n"
"\n"
"QTabBar::tab{\n"
"width: 0; \n"
"height: 0;\n"
"margin: 0; \n"
"padding: 0; \n"
"border: none\n"
"}")
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(370, 40, 151, 30))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_1 = QtWidgets.QLabel(self.tab)
        self.label_1.setGeometry(QtCore.QRect(1190, 40, 151, 30))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(140, 110, 640, 480))
        self.label_11.setStyleSheet("#label_11{\n"
"    background-color:black\n"
"}")
        self.label_11.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_22 = QtWidgets.QLabel(self.tab)
        self.label_22.setGeometry(QtCore.QRect(930, 110, 640, 480))
        self.label_22.setStyleSheet("#label_22{\n"
"    background-color:black\n"
"}")
        self.label_22.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_22.setLineWidth(1)
        self.label_22.setMidLineWidth(0)
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.but = QtWidgets.QPushButton(self.tab)
        self.but.setGeometry(QtCore.QRect(150, 690, 161, 46))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.but.setFont(font)
        self.but.setStyleSheet("/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:20pt;\n"
"    /*背景颜色*/  \n"
"    color: rgb(255, 255, 255);\n"
"    background-color:rgb(14 , 150 , 254);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:16px;\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(44 , 137 , 255);\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(14 , 135 , 228);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        self.but.setCheckable(False)
        self.but.setAutoDefault(False)
        self.but.setDefault(False)
        self.but.setFlat(False)
        self.but.setObjectName("but")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab)
        self.tabWidget_2.setGeometry(QtCore.QRect(340, 640, 1231, 320))
        self.tabWidget_2.setFocusPolicy(QtCore.Qt.FocusPolicy.TabFocus)
        self.tabWidget_2.setStyleSheet("#tabWidget_2{\n"
"    border: none\n"
"}\n"
"\n"
"#tab_3,#tab_4,#tab_6{\n"
"    background-color: rgb(240, 245, 250);\n"
"   \n"
"}\n"
"/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:20pt;\n"
"    /*字体颜色为白色*/    \n"
"    color: rgb(0, 0, 0);\n"
"    /*背景颜色*/  \n"
"    background-color: rgb(255, 255, 255);\n"
"    border-width:0px;  \n"
"    /*边框圆角半径为22像素*/ \n"
"    border-radius:5px;\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    border-width:0px;  \n"
"    background-color:#B0B8C1;\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    border-width:0px;  \n"
"    background-color:#B0B8C1;\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}\n"
"")
        self.tabWidget_2.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.tabWidget_2.setDocumentMode(True)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_ans_his = QtWidgets.QPlainTextEdit(self.tab_3)
        self.label_ans_his.setGeometry(QtCore.QRect(680, 0, 551, 318))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.label_ans_his.setFont(font)
        self.label_ans_his.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.label_ans_his.setAutoFillBackground(False)
        self.label_ans_his.setStyleSheet("")
        self.label_ans_his.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.label_ans_his.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.label_ans_his.setReadOnly(True)
        self.label_ans_his.setBackgroundVisible(False)
        self.label_ans_his.setCenterOnScroll(False)
        self.label_ans_his.setObjectName("label_ans_his")
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setGeometry(QtCore.QRect(10, 150, 101, 29))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(False)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("font: 700 17pt \"Microsoft YaHei UI\";\n"
"color: rgb(0, 40, 120);")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab_3)
        self.label_14.setGeometry(QtCore.QRect(10, 0, 101, 29))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(False)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("font: 700 17pt \"Microsoft YaHei UI\";\n"
"color: rgb(0, 40, 120);")
        self.label_14.setObjectName("label_14")
        self.label_16 = QtWidgets.QLabel(self.tab_3)
        self.label_16.setGeometry(QtCore.QRect(60, 30, 41, 29))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("font: 700 16pt \"Microsoft YaHei UI\";")
        self.label_16.setObjectName("label_16")
        self.label_com_in_en = QtWidgets.QLabel(self.tab_3)
        self.label_com_in_en.setGeometry(QtCore.QRect(30, 35, 20, 20))
        self.label_com_in_en.setStyleSheet("border-radius: 10px;      \n"
"background: red；        ")
        self.label_com_in_en.setText("")
        self.label_com_in_en.setObjectName("label_com_in_en")
        self.label_18 = QtWidgets.QLabel(self.tab_3)
        self.label_18.setGeometry(QtCore.QRect(60, 60, 91, 29))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("font: 700 16pt \"Microsoft YaHei UI\";")
        self.label_18.setObjectName("label_18")
        self.label_com_in_do = QtWidgets.QLabel(self.tab_3)
        self.label_com_in_do.setGeometry(QtCore.QRect(30, 65, 20, 20))
        self.label_com_in_do.setStyleSheet("\n"
"border-radius: 10px;      \n"
"background: red；        ")
        self.label_com_in_do.setText("")
        self.label_com_in_do.setObjectName("label_com_in_do")
        self.label__com_out_readly = QtWidgets.QLabel(self.tab_3)
        self.label__com_out_readly.setGeometry(QtCore.QRect(30, 215, 20, 20))
        self.label__com_out_readly.setStyleSheet("border-radius: 10px;      \n"
"background: red；        ")
        self.label__com_out_readly.setText("")
        self.label__com_out_readly.setObjectName("label__com_out_readly")
        self.label_com_out_bad = QtWidgets.QLabel(self.tab_3)
        self.label_com_out_bad.setGeometry(QtCore.QRect(30, 245, 20, 20))
        self.label_com_out_bad.setStyleSheet("border-radius: 10px;      \n"
"background: red；        ")
        self.label_com_out_bad.setText("")
        self.label_com_out_bad.setObjectName("label_com_out_bad")
        self.label_27 = QtWidgets.QLabel(self.tab_3)
        self.label_27.setGeometry(QtCore.QRect(60, 180, 41, 29))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("font: 700 16pt \"Microsoft YaHei UI\";")
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.tab_3)
        self.label_28.setGeometry(QtCore.QRect(60, 240, 91, 29))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("font: 700 16pt \"Microsoft YaHei UI\";")
        self.label_28.setObjectName("label_28")
        self.label_com_out_power = QtWidgets.QLabel(self.tab_3)
        self.label_com_out_power.setGeometry(QtCore.QRect(30, 185, 20, 20))
        self.label_com_out_power.setStyleSheet("\n"
"border-radius: 10px;      \n"
"background-color: rgb(0, 250, 0);")
        self.label_com_out_power.setText("")
        self.label_com_out_power.setObjectName("label_com_out_power")
        self.label_31 = QtWidgets.QLabel(self.tab_3)
        self.label_31.setGeometry(QtCore.QRect(60, 210, 91, 29))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("font: 700 16pt \"Microsoft YaHei UI\";")
        self.label_31.setObjectName("label_31")
        self.label_com_in_clean = QtWidgets.QLabel(self.tab_3)
        self.label_com_in_clean.setGeometry(QtCore.QRect(30, 95, 20, 20))
        self.label_com_in_clean.setStyleSheet("border-radius: 10px;      \n"
"background: red；        ")
        self.label_com_in_clean.setText("")
        self.label_com_in_clean.setObjectName("label_com_in_clean")
        self.label_21 = QtWidgets.QLabel(self.tab_3)
        self.label_21.setGeometry(QtCore.QRect(60, 90, 91, 29))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("font: 700 16pt \"Microsoft YaHei UI\";")
        self.label_21.setObjectName("label_21")
        self.label_30 = QtWidgets.QLabel(self.tab_3)
        self.label_30.setGeometry(QtCore.QRect(190, 0, 101, 29))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(False)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("font: 700 17pt \"Microsoft YaHei UI\";\n"
"color: rgb(0, 40, 120);")
        self.label_30.setObjectName("label_30")
        self.label_bad_str = QtWidgets.QLabel(self.tab_3)
        self.label_bad_str.setGeometry(QtCore.QRect(190, 30, 191, 281))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        self.label_bad_str.setFont(font)
        self.label_bad_str.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_bad_str.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_bad_str.setObjectName("label_bad_str")
        self.label_32 = QtWidgets.QLabel(self.tab_3)
        self.label_32.setGeometry(QtCore.QRect(395, 0, 151, 29))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(False)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("font: 700 17pt \"Microsoft YaHei UI\";\n"
"color: rgb(0, 40, 120);")
        self.label_32.setObjectName("label_32")
        self.label_15 = QtWidgets.QLabel(self.tab_3)
        self.label_15.setGeometry(QtCore.QRect(395, 30, 91, 31))
        self.label_15.setStyleSheet("font: 700 16pt \"Microsoft YaHei UI\";")
        self.label_15.setObjectName("label_15")
        self.label_ans_time = QtWidgets.QLabel(self.tab_3)
        self.label_ans_time.setGeometry(QtCore.QRect(490, 30, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.label_ans_time.setFont(font)
        self.label_ans_time.setStyleSheet("")
        self.label_ans_time.setObjectName("label_ans_time")
        self.label_37 = QtWidgets.QLabel(self.tab_3)
        self.label_37.setGeometry(QtCore.QRect(395, 120, 111, 31))
        self.label_37.setStyleSheet("font: 700 16pt \"Microsoft YaHei UI\";")
        self.label_37.setObjectName("label_37")
        self.label_ans_reliability = QtWidgets.QLabel(self.tab_3)
        self.label_ans_reliability.setGeometry(QtCore.QRect(510, 120, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.label_ans_reliability.setFont(font)
        self.label_ans_reliability.setStyleSheet("")
        self.label_ans_reliability.setObjectName("label_ans_reliability")
        self.label_39 = QtWidgets.QLabel(self.tab_3)
        self.label_39.setGeometry(QtCore.QRect(395, 180, 91, 31))
        self.label_39.setStyleSheet("font: 700 16pt \"Microsoft YaHei UI\";")
        self.label_39.setObjectName("label_39")
        self.label_ans_str = QtWidgets.QLabel(self.tab_3)
        self.label_ans_str.setGeometry(QtCore.QRect(395, 210, 271, 111))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.label_ans_str.setFont(font)
        self.label_ans_str.setStyleSheet("")
        self.label_ans_str.setText("")
        self.label_ans_str.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_ans_str.setObjectName("label_ans_str")
        self.label_33 = QtWidgets.QLabel(self.tab_3)
        self.label_33.setGeometry(QtCore.QRect(395, 90, 111, 31))
        self.label_33.setStyleSheet("font: 700 16pt \"Microsoft YaHei UI\";")
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.tab_3)
        self.label_34.setGeometry(QtCore.QRect(395, 60, 91, 31))
        self.label_34.setStyleSheet("font: 700 16pt \"Microsoft YaHei UI\";")
        self.label_34.setObjectName("label_34")
        self.label_ans_bad_num = QtWidgets.QLabel(self.tab_3)
        self.label_ans_bad_num.setGeometry(QtCore.QRect(510, 90, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.label_ans_bad_num.setFont(font)
        self.label_ans_bad_num.setStyleSheet("")
        self.label_ans_bad_num.setObjectName("label_ans_bad_num")
        self.label_ans_2 = QtWidgets.QLabel(self.tab_3)
        self.label_ans_2.setGeometry(QtCore.QRect(490, 60, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.label_ans_2.setFont(font)
        self.label_ans_2.setStyleSheet("")
        self.label_ans_2.setObjectName("label_ans_2")
        self.label_35 = QtWidgets.QLabel(self.tab_3)
        self.label_35.setGeometry(QtCore.QRect(395, 150, 91, 31))
        self.label_35.setStyleSheet("font: 700 16pt \"Microsoft YaHei UI\";")
        self.label_35.setObjectName("label_35")
        self.label_ans_optimize = QtWidgets.QLabel(self.tab_3)
        self.label_ans_optimize.setGeometry(QtCore.QRect(490, 150, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.label_ans_optimize.setFont(font)
        self.label_ans_optimize.setStyleSheet("")
        self.label_ans_optimize.setObjectName("label_ans_optimize")
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.widget_2 = QtWidgets.QWidget(self.tab_4)
        self.widget_2.setGeometry(QtCore.QRect(655, 0, 576, 320))
        self.widget_2.setStyleSheet("#widget_2{\n"
"background-color:#DADADA\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.Buttonl = QtWidgets.QPushButton(self.widget_2)
        self.Buttonl.setGeometry(QtCore.QRect(20, 240, 76, 65))
        self.Buttonl.setStyleSheet("")
        self.Buttonl.setObjectName("Buttonl")
        self.Button8 = QtWidgets.QPushButton(self.widget_2)
        self.Button8.setGeometry(QtCore.QRect(110, 15, 76, 65))
        self.Button8.setStyleSheet("")
        self.Button8.setObjectName("Button8")
        self.Button7 = QtWidgets.QPushButton(self.widget_2)
        self.Button7.setGeometry(QtCore.QRect(20, 15, 76, 65))
        self.Button7.setStyleSheet("")
        self.Button7.setObjectName("Button7")
        self.Buttonent = QtWidgets.QPushButton(self.widget_2)
        self.Buttonent.setGeometry(QtCore.QRect(480, 165, 76, 141))
        self.Buttonent.setStyleSheet("/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:20pt;\n"
"    /*字体颜色为白色*/    \n"
"    color: rgb(0, 0, 0);\n"
"    /*背景颜色*/  \n"
"    background-color: #C8CCD1;\n"
"    border-width:0px;  \n"
"    /*边框圆角半径为22像素*/ \n"
"    border-radius:5px;\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    border-width:0px;  \n"
"    background-color:#B0B8C1;\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    border-width:0px;  \n"
"    background-color:#B0B8C1;\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}\n"
"")
        self.Buttonent.setObjectName("Buttonent")
        self.Button1 = QtWidgets.QPushButton(self.widget_2)
        self.Button1.setGeometry(QtCore.QRect(20, 165, 76, 65))
        self.Button1.setObjectName("Button1")
        self.Buttondd = QtWidgets.QPushButton(self.widget_2)
        self.Buttondd.setGeometry(QtCore.QRect(300, 165, 76, 65))
        self.Buttondd.setObjectName("Buttondd")
        self.Button9 = QtWidgets.QPushButton(self.widget_2)
        self.Button9.setGeometry(QtCore.QRect(200, 15, 71, 65))
        self.Button9.setStyleSheet("")
        self.Button9.setObjectName("Button9")
        self.Button3 = QtWidgets.QPushButton(self.widget_2)
        self.Button3.setGeometry(QtCore.QRect(200, 165, 71, 65))
        self.Button3.setObjectName("Button3")
        self.Button4 = QtWidgets.QPushButton(self.widget_2)
        self.Button4.setGeometry(QtCore.QRect(20, 90, 76, 65))
        self.Button4.setObjectName("Button4")
        self.Button0 = QtWidgets.QPushButton(self.widget_2)
        self.Button0.setGeometry(QtCore.QRect(110, 240, 76, 65))
        self.Button0.setStyleSheet("")
        self.Button0.setObjectName("Button0")
        self.Button6 = QtWidgets.QPushButton(self.widget_2)
        self.Button6.setGeometry(QtCore.QRect(200, 90, 71, 65))
        self.Button6.setObjectName("Button6")
        self.Button2 = QtWidgets.QPushButton(self.widget_2)
        self.Button2.setGeometry(QtCore.QRect(110, 165, 76, 65))
        self.Button2.setObjectName("Button2")
        self.Buttonback = QtWidgets.QPushButton(self.widget_2)
        self.Buttonback.setGeometry(QtCore.QRect(391, 15, 166, 65))
        self.Buttonback.setStyleSheet("/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:20pt;\n"
"    /*字体颜色为白色*/    \n"
"    color: rgb(0, 0, 0);\n"
"    /*背景颜色*/  \n"
"    background-color: #C8CCD1;\n"
"    border-width:0px;  \n"
"    /*边框圆角半径为22像素*/ \n"
"    border-radius:5px;\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    border-width:0px;  \n"
"    background-color:#B0B8C1;\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    border-width:0px;  \n"
"    background-color:#B0B8C1;\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        self.Buttonback.setObjectName("Buttonback")
        self.Button5 = QtWidgets.QPushButton(self.widget_2)
        self.Button5.setGeometry(QtCore.QRect(110, 90, 76, 65))
        self.Button5.setObjectName("Button5")
        self.Buttoni = QtWidgets.QPushButton(self.widget_2)
        self.Buttoni.setGeometry(QtCore.QRect(300, 240, 76, 65))
        self.Buttoni.setStyleSheet("")
        self.Buttoni.setObjectName("Buttoni")
        self.Buttond = QtWidgets.QPushButton(self.widget_2)
        self.Buttond.setGeometry(QtCore.QRect(200, 240, 71, 65))
        self.Buttond.setStyleSheet("")
        self.Buttond.setObjectName("Buttond")
        self.Buttonyear = QtWidgets.QPushButton(self.widget_2)
        self.Buttonyear.setGeometry(QtCore.QRect(391, 90, 76, 65))
        self.Buttonyear.setObjectName("Buttonyear")
        self.Buttonmonth = QtWidgets.QPushButton(self.widget_2)
        self.Buttonmonth.setGeometry(QtCore.QRect(390, 165, 76, 65))
        self.Buttonmonth.setObjectName("Buttonmonth")
        self.Buttonday = QtWidgets.QPushButton(self.widget_2)
        self.Buttonday.setGeometry(QtCore.QRect(390, 240, 76, 65))
        self.Buttonday.setObjectName("Buttonday")
        self.Buttonc = QtWidgets.QPushButton(self.widget_2)
        self.Buttonc.setGeometry(QtCore.QRect(480, 90, 76, 65))
        self.Buttonc.setStyleSheet("/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:20pt;\n"
"    /*字体颜色为白色*/    \n"
"    color: rgb(0, 0, 0);\n"
"    /*背景颜色*/  \n"
"    background-color: #C8CCD1;\n"
"    border-width:0px;  \n"
"    /*边框圆角半径为22像素*/ \n"
"    border-radius:5px;\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    border-width:0px;  \n"
"    background-color:#B0B8C1;\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    border-width:0px;  \n"
"    background-color:#B0B8C1;\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        self.Buttonc.setObjectName("Buttonc")
        self.Buttoncn = QtWidgets.QPushButton(self.widget_2)
        self.Buttoncn.setGeometry(QtCore.QRect(300, 14, 76, 65))
        self.Buttoncn.setStyleSheet("/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    font: 600 16pt \"Microsoft YaHei UI\";\n"
"    /*字体颜色为白色*/    \n"
"    color: rgb(0, 0, 0);\n"
"    /*背景颜色*/  \n"
"    background-color: #C8CCD1;\n"
"    border-width:0px;  \n"
"    /*边框圆角半径为22像素*/ \n"
"    border-radius:5px;\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    border-width:0px;  \n"
"    background-color:#B0B8C1;\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    border-width:0px;  \n"
"    background-color:#B0B8C1;\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        self.Buttoncn.setObjectName("Buttoncn")
        self.Buttoncn_2 = QtWidgets.QPushButton(self.widget_2)
        self.Buttoncn_2.setGeometry(QtCore.QRect(300, 90, 76, 65))
        self.Buttoncn_2.setStyleSheet("/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    font: 600 16pt \"Microsoft YaHei UI\";\n"
"    /*字体颜色为白色*/    \n"
"    color: rgb(0, 0, 0);\n"
"    /*背景颜色*/  \n"
"    background-color: #C8CCD1;\n"
"    border-width:0px;  \n"
"    /*边框圆角半径为22像素*/ \n"
"    border-radius:5px;\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    border-width:0px;  \n"
"    background-color:#B0B8C1;\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    border-width:0px;  \n"
"    background-color:#B0B8C1;\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        self.Buttoncn_2.setObjectName("Buttoncn_2")
        self.inin = QtWidgets.QTextEdit(self.tab_4)
        self.inin.setGeometry(QtCore.QRect(360, 60, 271, 111))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setKerning(False)
        self.inin.setFont(font)
        self.inin.setStyleSheet("")
        self.inin.setReadOnly(True)
        self.inin.setMarkdown("")
        self.inin.setObjectName("inin")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_4.setGeometry(QtCore.QRect(570, 245, 51, 31))
        self.pushButton_4.setStyleSheet("/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"font: 23pt \"Microsoft YaHei UI\";\n"
"    border-radius:10px;\n"
"}\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    border-radius:10px;\n"
"font: 23pt \"Microsoft YaHei UI\";\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    border-radius:10px;\n"
"font: 23pt \"Microsoft YaHei UI\";\n"
"}\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_5.setGeometry(QtCore.QRect(440, 245, 51, 31))
        self.pushButton_5.setStyleSheet("/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    border-radius:10px;\n"
"font: 30pt \"Microsoft YaHei UI\";\n"
"}\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    border-radius:10px;\n"
"font: 30pt \"Microsoft YaHei UI\";\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    border-radius:10px;\n"
"font: 30pt \"Microsoft YaHei UI\";\n"
"}\n"
"\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_bad = QtWidgets.QLabel(self.tab_4)
        self.label_bad.setGeometry(QtCore.QRect(500, 245, 61, 31))
        self.label_bad.setStyleSheet("#label_bad{\n"
"  /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:20pt;\n"
"    /*字体颜色为白色*/    \n"
"    color: rgb(255, 0, 0);\n"
"    /*背景颜色*/  \n"
"    background-color: rgb(255, 255, 255);\n"
"    border-width:0px;  \n"
"    /*边框圆角半径为22像素*/ \n"
"    border-radius:10px;\n"
"}")
        self.label_bad.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_bad.setObjectName("label_bad")
        self.label_bad_2 = QtWidgets.QLabel(self.tab_4)
        self.label_bad_2.setGeometry(QtCore.QRect(430, 190, 131, 41))
        self.label_bad_2.setStyleSheet("#label_bad_2{\n"
"  /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:20pt;\n"
"    /*字体颜色为白色*/    \n"
"    color: rgb(0, 0, 0);\n"
"    /*背景颜色*/  \n"
"    background-color: #C5D8F1;\n"
"    border-width:0px;  \n"
"    /*边框圆角半径为22像素*/ \n"
"    border-radius:13px;\n"
"}")
        self.label_bad_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_bad_2.setObjectName("label_bad_2")
        self.label_bad_3 = QtWidgets.QLabel(self.tab_4)
        self.label_bad_3.setGeometry(QtCore.QRect(410, 0, 181, 41))
        self.label_bad_3.setStyleSheet("#label_bad_3{\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:20pt;\n"
"    /*字体颜色为白色*/    \n"
"    color: rgb(0, 0, 0);\n"
"    /*背景颜色*/  \n"
"    background-color: #C5D8F1;\n"
"    border-width:0px;  \n"
"    /*边框圆角半径为22像素*/ \n"
"    border-radius:13px;\n"
"}\n"
"")
        self.label_bad_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_bad_3.setObjectName("label_bad_3")
        self.label_6 = QtWidgets.QLabel(self.tab_4)
        self.label_6.setGeometry(QtCore.QRect(60, 0, 211, 41))
        self.label_6.setStyleSheet("#label_6{\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:20pt;\n"
"    /*字体颜色为白色*/    \n"
"    color: rgb(0, 0, 0);\n"
"    /*背景颜色*/  \n"
"    background-color: #C5D8F1;\n"
"    border-width:0px;  \n"
"    /*边框圆角半径为22像素*/ \n"
"    border-radius:13px;\n"
"}\n"
"")
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_10 = QtWidgets.QLabel(self.tab_4)
        self.label_10.setGeometry(QtCore.QRect(20, 50, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.widget_3 = QtWidgets.QWidget(self.tab_4)
        self.widget_3.setGeometry(QtCore.QRect(150, 45, 181, 181))
        self.widget_3.setObjectName("widget_3")
        self.radioButton_hisall = QtWidgets.QRadioButton(self.widget_3)
        self.radioButton_hisall.setGeometry(QtCore.QRect(10, 106, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radioButton_hisall.setFont(font)
        self.radioButton_hisall.setAutoRepeat(True)
        self.radioButton_hisall.setAutoExclusive(False)
        self.radioButton_hisall.setObjectName("radioButton_hisall")
        self.radioButton_his = QtWidgets.QRadioButton(self.widget_3)
        self.radioButton_his.setGeometry(QtCore.QRect(10, 36, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radioButton_his.setFont(font)
        self.radioButton_his.setAutoRepeat(True)
        self.radioButton_his.setAutoExclusive(False)
        self.radioButton_his.setObjectName("radioButton_his")
        self.radioButton_hisauto = QtWidgets.QRadioButton(self.widget_3)
        self.radioButton_hisauto.setGeometry(QtCore.QRect(10, 71, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radioButton_hisauto.setFont(font)
        self.radioButton_hisauto.setAutoRepeat(True)
        self.radioButton_hisauto.setAutoExclusive(False)
        self.radioButton_hisauto.setObjectName("radioButton_hisauto")
        self.label_17 = QtWidgets.QLabel(self.widget_3)
        self.label_17.setGeometry(QtCore.QRect(10, 5, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.radioButton_hsv = QtWidgets.QRadioButton(self.widget_3)
        self.radioButton_hsv.setGeometry(QtCore.QRect(10, 141, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radioButton_hsv.setFont(font)
        self.radioButton_hsv.setAutoRepeat(True)
        self.radioButton_hsv.setAutoExclusive(False)
        self.radioButton_hsv.setObjectName("radioButton_hsv")
        self.widget_4 = QtWidgets.QWidget(self.tab_4)
        self.widget_4.setGeometry(QtCore.QRect(20, 220, 311, 101))
        self.widget_4.setObjectName("widget_4")
        self.label_12 = QtWidgets.QLabel(self.widget_4)
        self.label_12.setGeometry(QtCore.QRect(0, 1, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.radioButtongauss = QtWidgets.QRadioButton(self.widget_4)
        self.radioButtongauss.setGeometry(QtCore.QRect(0, 35, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radioButtongauss.setFont(font)
        self.radioButtongauss.setCheckable(True)
        self.radioButtongauss.setAutoRepeat(False)
        self.radioButtongauss.setAutoExclusive(False)
        self.radioButtongauss.setObjectName("radioButtongauss")
        self.radioButtonclose = QtWidgets.QRadioButton(self.widget_4)
        self.radioButtonclose.setGeometry(QtCore.QRect(140, 70, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radioButtonclose.setFont(font)
        self.radioButtonclose.setCheckable(True)
        self.radioButtonclose.setAutoRepeat(False)
        self.radioButtonclose.setAutoExclusive(True)
        self.radioButtonclose.setObjectName("radioButtonclose")
        self.radioButtonopen = QtWidgets.QRadioButton(self.widget_4)
        self.radioButtonopen.setGeometry(QtCore.QRect(140, 35, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radioButtonopen.setFont(font)
        self.radioButtonopen.setCheckable(True)
        self.radioButtonopen.setAutoRepeat(False)
        self.radioButtonopen.setAutoExclusive(True)
        self.radioButtonopen.setObjectName("radioButtonopen")
        self.radioButtoneven = QtWidgets.QRadioButton(self.widget_4)
        self.radioButtoneven.setGeometry(QtCore.QRect(0, 70, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radioButtoneven.setFont(font)
        self.radioButtoneven.setAutoRepeat(False)
        self.radioButtoneven.setAutoExclusive(False)
        self.radioButtoneven.setObjectName("radioButtoneven")
        self.pushButton_open2 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_open2.setGeometry(QtCore.QRect(270, 40, 41, 24))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        self.pushButton_open2.setFont(font)
        self.pushButton_open2.setStyleSheet("font: 18pt \"Microsoft YaHei UI\";\n"
"background-color: rgb(225, 225, 225)")
        self.pushButton_open2.setObjectName("pushButton_open2")
        self.pushButton_close1 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_close1.setGeometry(QtCore.QRect(220, 75, 31, 24))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        self.pushButton_close1.setFont(font)
        self.pushButton_close1.setStyleSheet("font: 18pt \"Microsoft YaHei UI\";\n"
"background-color: rgb(225, 225, 225)")
        self.pushButton_close1.setObjectName("pushButton_close1")
        self.pushButton_open1 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_open1.setGeometry(QtCore.QRect(220, 40, 31, 24))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        self.pushButton_open1.setFont(font)
        self.pushButton_open1.setStyleSheet("font: 18pt \"Microsoft YaHei UI\";\n"
"background-color: rgb(225, 225, 225)")
        self.pushButton_open1.setObjectName("pushButton_open1")
        self.label_open = QtWidgets.QLabel(self.widget_4)
        self.label_open.setGeometry(QtCore.QRect(242, 40, 40, 24))
        self.label_open.setStyleSheet("font: 18pt \"Microsoft YaHei UI\";\n"
"background-color: rgb(225, 225, 225)")
        self.label_open.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_open.setObjectName("label_open")
        self.label_close = QtWidgets.QLabel(self.widget_4)
        self.label_close.setGeometry(QtCore.QRect(242, 75, 40, 24))
        self.label_close.setStyleSheet("font: 18pt \"Microsoft YaHei UI\";\n"
"background-color: rgb(225, 225, 225)")
        self.label_close.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_close.setObjectName("label_close")
        self.pushButton_close2 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_close2.setGeometry(QtCore.QRect(270, 75, 41, 24))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        self.pushButton_close2.setFont(font)
        self.pushButton_close2.setStyleSheet("font: 18pt \"Microsoft YaHei UI\";\n"
"background-color: rgb(225, 225, 225)")
        self.pushButton_close2.setObjectName("pushButton_close2")
        self.label_12.raise_()
        self.radioButtongauss.raise_()
        self.radioButtonclose.raise_()
        self.radioButtonopen.raise_()
        self.radioButtoneven.raise_()
        self.label_open.raise_()
        self.pushButton_open2.raise_()
        self.label_close.raise_()
        self.pushButton_close1.raise_()
        self.pushButton_open1.raise_()
        self.pushButton_close2.raise_()
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_6.setGeometry(QtCore.QRect(440, 285, 51, 31))
        self.pushButton_6.setStyleSheet("/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    border-radius:10px;\n"
"font: 30pt \"Microsoft YaHei UI\";\n"
"}\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    border-radius:10px;\n"
"font: 30pt \"Microsoft YaHei UI\";\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    border-radius:10px;\n"
"font: 30pt \"Microsoft YaHei UI\";\n"
"}\n"
"\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_bad_4 = QtWidgets.QLabel(self.tab_4)
        self.label_bad_4.setGeometry(QtCore.QRect(500, 285, 61, 31))
        self.label_bad_4.setStyleSheet("  /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:20pt;\n"
"    /*字体颜色为白色*/    \n"
"    color: rgb(255, 0, 0);\n"
"    /*背景颜色*/  \n"
"    background-color: rgb(255, 255, 255);\n"
"    border-width:0px;  \n"
"    /*边框圆角半径为22像素*/ \n"
"    border-radius:10px;\n"
"")
        self.label_bad_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_bad_4.setObjectName("label_bad_4")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_7.setGeometry(QtCore.QRect(570, 285, 51, 31))
        self.pushButton_7.setStyleSheet("/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"font: 23pt \"Microsoft YaHei UI\";\n"
"    border-radius:10px;\n"
"}\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    border-radius:10px;\n"
"font: 23pt \"Microsoft YaHei UI\";\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    border-radius:10px;\n"
"font: 23pt \"Microsoft YaHei UI\";\n"
"}\n"
"")
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_5 = QtWidgets.QLabel(self.tab_4)
        self.label_5.setGeometry(QtCore.QRect(355, 245, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.label_5.setFont(font)
        self.label_5.setToolTipDuration(-1)
        self.label_5.setStyleSheet("#{\n"
"letter-spacing : 0pt;\n"
"}")
        self.label_5.setLineWidth(1)
        self.label_5.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_5.setIndent(-1)
        self.label_5.setObjectName("label_5")
        self.label_20 = QtWidgets.QLabel(self.tab_4)
        self.label_20.setGeometry(QtCore.QRect(355, 285, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.radioButtonmould = QtWidgets.QRadioButton(self.tab_4)
        self.radioButtonmould.setGeometry(QtCore.QRect(20, 187, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radioButtonmould.setFont(font)
        self.radioButtonmould.setCheckable(True)
        self.radioButtonmould.setAutoRepeat(False)
        self.radioButtonmould.setAutoExclusive(True)
        self.radioButtonmould.setObjectName("radioButtonmould")
        self.radioButtongray = QtWidgets.QRadioButton(self.tab_4)
        self.radioButtongray.setGeometry(QtCore.QRect(20, 117, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radioButtongray.setFont(font)
        self.radioButtongray.setIconSize(QtCore.QSize(16, 16))
        self.radioButtongray.setCheckable(True)
        self.radioButtongray.setAutoRepeat(False)
        self.radioButtongray.setAutoExclusive(True)
        self.radioButtongray.setObjectName("radioButtongray")
        self.radioButtoncolor = QtWidgets.QRadioButton(self.tab_4)
        self.radioButtoncolor.setGeometry(QtCore.QRect(20, 82, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radioButtoncolor.setFont(font)
        self.radioButtoncolor.setIconSize(QtCore.QSize(16, 16))
        self.radioButtoncolor.setCheckable(True)
        self.radioButtoncolor.setAutoRepeat(False)
        self.radioButtoncolor.setAutoExclusive(True)
        self.radioButtoncolor.setObjectName("radioButtoncolor")
        self.radioButtonblack = QtWidgets.QRadioButton(self.tab_4)
        self.radioButtonblack.setGeometry(QtCore.QRect(20, 152, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radioButtonblack.setFont(font)
        self.radioButtonblack.setCheckable(True)
        self.radioButtonblack.setAutoRepeat(False)
        self.radioButtonblack.setAutoExclusive(True)
        self.radioButtonblack.setObjectName("radioButtonblack")
        self.widget_5 = QtWidgets.QWidget(self.tab_4)
        self.widget_5.setGeometry(QtCore.QRect(150, 45, 181, 211))
        self.widget_5.setObjectName("widget_5")
        self.radioButton_otus = QtWidgets.QRadioButton(self.widget_5)
        self.radioButton_otus.setGeometry(QtCore.QRect(10, 36, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radioButton_otus.setFont(font)
        self.radioButton_otus.setAutoRepeat(False)
        self.radioButton_otus.setAutoExclusive(True)
        self.radioButton_otus.setObjectName("radioButton_otus")
        self.radioButton_mean = QtWidgets.QRadioButton(self.widget_5)
        self.radioButton_mean.setGeometry(QtCore.QRect(10, 71, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radioButton_mean.setFont(font)
        self.radioButton_mean.setAutoRepeat(False)
        self.radioButton_mean.setAutoExclusive(True)
        self.radioButton_mean.setObjectName("radioButton_mean")
        self.label_19 = QtWidgets.QLabel(self.widget_5)
        self.label_19.setGeometry(QtCore.QRect(10, 5, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.radioButton_200 = QtWidgets.QRadioButton(self.widget_5)
        self.radioButton_200.setGeometry(QtCore.QRect(10, 106, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radioButton_200.setFont(font)
        self.radioButton_200.setAutoRepeat(False)
        self.radioButton_200.setAutoExclusive(True)
        self.radioButton_200.setObjectName("radioButton_200")
        self.widget_7 = QtWidgets.QWidget(self.widget_5)
        self.widget_7.setGeometry(QtCore.QRect(10, 140, 171, 71))
        self.widget_7.setObjectName("widget_7")
        self.label_26 = QtWidgets.QLabel(self.widget_7)
        self.label_26.setGeometry(QtCore.QRect(20, 35, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.pushButton_jd1 = QtWidgets.QPushButton(self.widget_7)
        self.pushButton_jd1.setGeometry(QtCore.QRect(70, 5, 31, 24))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        self.pushButton_jd1.setFont(font)
        self.pushButton_jd1.setStyleSheet("font: 18pt \"Microsoft YaHei UI\";\n"
"background-color: rgb(225, 225, 225)")
        self.pushButton_jd1.setObjectName("pushButton_jd1")
        self.label_jd = QtWidgets.QLabel(self.widget_7)
        self.label_jd.setGeometry(QtCore.QRect(97, 5, 40, 24))
        self.label_jd.setStyleSheet("font: 18pt \"Microsoft YaHei UI\";\n"
"background-color: rgb(225, 225, 225)")
        self.label_jd.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_jd.setObjectName("label_jd")
        self.label_lb = QtWidgets.QLabel(self.widget_7)
        self.label_lb.setGeometry(QtCore.QRect(97, 40, 40, 24))
        self.label_lb.setStyleSheet("font: 18pt \"Microsoft YaHei UI\";\n"
"background-color: rgb(225, 225, 225)")
        self.label_lb.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_lb.setObjectName("label_lb")
        self.pushButton_lb2 = QtWidgets.QPushButton(self.widget_7)
        self.pushButton_lb2.setGeometry(QtCore.QRect(130, 40, 41, 24))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        self.pushButton_lb2.setFont(font)
        self.pushButton_lb2.setStyleSheet("font: 18pt \"Microsoft YaHei UI\";\n"
"background-color: rgb(225, 225, 225)")
        self.pushButton_lb2.setObjectName("pushButton_lb2")
        self.pushButton_jd2 = QtWidgets.QPushButton(self.widget_7)
        self.pushButton_jd2.setGeometry(QtCore.QRect(130, 5, 41, 24))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        self.pushButton_jd2.setFont(font)
        self.pushButton_jd2.setStyleSheet("font: 18pt \"Microsoft YaHei UI\";\n"
"background-color: rgb(225, 225, 225)")
        self.pushButton_jd2.setObjectName("pushButton_jd2")
        self.label_25 = QtWidgets.QLabel(self.widget_7)
        self.label_25.setGeometry(QtCore.QRect(20, 0, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.pushButton_lb1 = QtWidgets.QPushButton(self.widget_7)
        self.pushButton_lb1.setGeometry(QtCore.QRect(70, 40, 31, 24))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        self.pushButton_lb1.setFont(font)
        self.pushButton_lb1.setStyleSheet("font: 18pt \"Microsoft YaHei UI\";\n"
"background-color: rgb(225, 225, 225)")
        self.pushButton_lb1.setObjectName("pushButton_lb1")
        self.widget_8 = QtWidgets.QWidget(self.widget_5)
        self.widget_8.setGeometry(QtCore.QRect(10, 140, 171, 71))
        self.widget_8.setObjectName("widget_8")
        self.pushButton_jd1_2 = QtWidgets.QPushButton(self.widget_8)
        self.pushButton_jd1_2.setGeometry(QtCore.QRect(70, 5, 31, 24))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        self.pushButton_jd1_2.setFont(font)
        self.pushButton_jd1_2.setStyleSheet("font: 18pt \"Microsoft YaHei UI\";\n"
"background-color: rgb(225, 225, 225)")
        self.pushButton_jd1_2.setObjectName("pushButton_jd1_2")
        self.label_jd_2 = QtWidgets.QLabel(self.widget_8)
        self.label_jd_2.setGeometry(QtCore.QRect(97, 5, 40, 24))
        self.label_jd_2.setStyleSheet("font: 18pt \"Microsoft YaHei UI\";\n"
"background-color: rgb(225, 225, 225)")
        self.label_jd_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_jd_2.setObjectName("label_jd_2")
        self.pushButton_jd2_2 = QtWidgets.QPushButton(self.widget_8)
        self.pushButton_jd2_2.setGeometry(QtCore.QRect(130, 5, 41, 24))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        self.pushButton_jd2_2.setFont(font)
        self.pushButton_jd2_2.setStyleSheet("font: 18pt \"Microsoft YaHei UI\";\n"
"background-color: rgb(225, 225, 225)")
        self.pushButton_jd2_2.setObjectName("pushButton_jd2_2")
        self.label_41 = QtWidgets.QLabel(self.widget_8)
        self.label_41.setGeometry(QtCore.QRect(20, 0, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.pushButton_lb1_2 = QtWidgets.QPushButton(self.widget_8)
        self.pushButton_lb1_2.setGeometry(QtCore.QRect(70, 40, 31, 24))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        self.pushButton_lb1_2.setFont(font)
        self.pushButton_lb1_2.setStyleSheet("font: 18pt \"Microsoft YaHei UI\";\n"
"background-color: rgb(225, 225, 225)")
        self.pushButton_lb1_2.setObjectName("pushButton_lb1_2")
        self.pushButton_lb2_2 = QtWidgets.QPushButton(self.widget_8)
        self.pushButton_lb2_2.setGeometry(QtCore.QRect(130, 40, 41, 24))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        self.pushButton_lb2_2.setFont(font)
        self.pushButton_lb2_2.setStyleSheet("font: 18pt \"Microsoft YaHei UI\";\n"
"background-color: rgb(225, 225, 225)")
        self.pushButton_lb2_2.setObjectName("pushButton_lb2_2")
        self.label_lb_2 = QtWidgets.QLabel(self.widget_8)
        self.label_lb_2.setGeometry(QtCore.QRect(97, 40, 40, 24))
        self.label_lb_2.setStyleSheet("font: 18pt \"Microsoft YaHei UI\";\n"
"background-color: rgb(225, 225, 225)")
        self.label_lb_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_lb_2.setObjectName("label_lb_2")
        self.label_42 = QtWidgets.QLabel(self.widget_8)
        self.label_42.setGeometry(QtCore.QRect(20, 35, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.widget_6 = QtWidgets.QWidget(self.tab_4)
        self.widget_6.setGeometry(QtCore.QRect(150, 44, 181, 151))
        self.widget_6.setObjectName("widget_6")
        self.radioButton_colorhis = QtWidgets.QRadioButton(self.widget_6)
        self.radioButton_colorhis.setGeometry(QtCore.QRect(10, 37, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radioButton_colorhis.setFont(font)
        self.radioButton_colorhis.setAutoRepeat(True)
        self.radioButton_colorhis.setAutoExclusive(False)
        self.radioButton_colorhis.setObjectName("radioButton_colorhis")
        self.label_29 = QtWidgets.QLabel(self.widget_6)
        self.label_29.setGeometry(QtCore.QRect(10, 5, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.tabWidget_2.addTab(self.tab_4, "")
        self.but_2 = QtWidgets.QPushButton(self.tab)
        self.but_2.setGeometry(QtCore.QRect(150, 810, 161, 46))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.but_2.setFont(font)
        self.but_2.setStyleSheet("/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:20pt;\n"
"    /*字体颜色为白色*/    \n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(14 , 150 , 254);\n"
"    /*边框圆角半径为22像素*/ \n"
"    border-radius:16px;\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(44 , 137 , 255);\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(14 , 135 , 228);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        self.but_2.setCheckable(False)
        self.but_2.setAutoDefault(False)
        self.but_2.setDefault(False)
        self.but_2.setFlat(False)
        self.but_2.setObjectName("but_2")
        self.label_ans = QtWidgets.QLabel(self.tab)
        self.label_ans.setGeometry(QtCore.QRect(255, 640, 91, 30))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(False)
        self.label_ans.setFont(font)
        self.label_ans.setStyleSheet("font: 700 17pt \"Microsoft YaHei UI\";\n"
"color: rgb(0, 40, 120);")
        self.label_ans.setObjectName("label_ans")
        self.but_1 = QtWidgets.QPushButton(self.tab)
        self.but_1.setGeometry(QtCore.QRect(150, 750, 161, 46))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.but_1.setFont(font)
        self.but_1.setStyleSheet("/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:20pt;\n"
"    /*字体颜色为白色*/    \n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(14 , 150 , 254);\n"
"    /*边框圆角半径为22像素*/ \n"
"    border-radius:16px;\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(44 , 137 , 255);\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(14 , 135 , 228);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        self.but_1.setCheckable(False)
        self.but_1.setAutoDefault(False)
        self.but_1.setDefault(False)
        self.but_1.setFlat(False)
        self.but_1.setObjectName("but_1")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(145, 640, 101, 30))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(False)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("font: 700 17pt \"Microsoft YaHei UI\";\n"
"color: rgb(0, 40, 120);")
        self.label_9.setObjectName("label_9")
        self.but_3 = QtWidgets.QPushButton(self.tab)
        self.but_3.setGeometry(QtCore.QRect(150, 870, 161, 46))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.but_3.setFont(font)
        self.but_3.setStyleSheet("/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:20pt;\n"
"    /*字体颜色为白色*/    \n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(14 , 150 , 254);\n"
"    /*边框圆角半径为22像素*/ \n"
"    border-radius:16px;\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(44 , 137 , 255);\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(14 , 135 , 228);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        self.but_3.setCheckable(False)
        self.but_3.setAutoDefault(False)
        self.but_3.setDefault(False)
        self.but_3.setFlat(False)
        self.but_3.setObjectName("but_3")
        self.pushButtoncleanlearn = QtWidgets.QPushButton(self.tab)
        self.pushButtoncleanlearn.setGeometry(QtCore.QRect(150, 930, 161, 46))
        self.pushButtoncleanlearn.setStyleSheet("/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:20pt;\n"
"    /*背景颜色*/  \n"
"    color: rgb(255, 255, 255);\n"
"    background-color:rgb(255, 0, 0);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:16px;\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(255, 55, 55);\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(255, 0, 0);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        self.pushButtoncleanlearn.setObjectName("pushButtoncleanlearn")
        self.tabWidget.addTab(self.tab, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.label_7 = QtWidgets.QLabel(self.tab_5)
        self.label_7.setGeometry(QtCore.QRect(660, 80, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(False)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab_5)
        self.label_8.setGeometry(QtCore.QRect(150, 150, 1451, 831))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(False)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_8.setObjectName("label_8")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_23 = QtWidgets.QLabel(self.tab_2)
        self.label_23.setGeometry(QtCore.QRect(660, 80, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(False)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.tab_2)
        self.label_24.setGeometry(QtCore.QRect(150, 150, 1451, 831))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_24.setObjectName("label_24")
        self.tabWidget.addTab(self.tab_2, "")
        self.frame = QtWidgets.QFrame(self.widget1)
        self.frame.setEnabled(True)
        self.frame.setGeometry(QtCore.QRect(0, 0, 220, 1020))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(220, 1020))
        self.frame.setStyleSheet("#frame {\n"
"    background-color:#222D32\n"
"}\n"
"/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:20pt;\n"
"    /*字体颜色为白色*/    \n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    background-color:#222D32;\n"
"    /*边框圆角半径为22像素*/ \n"
"    border-radius:0px;\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:#3E484D;\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:#3E484D;\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.butmain = QtWidgets.QPushButton(self.frame)
        self.butmain.setGeometry(QtCore.QRect(0, 40, 220, 100))
        self.butmain.setStyleSheet("")
        self.butmain.setObjectName("butmain")
        self.buthelp = QtWidgets.QPushButton(self.frame)
        self.buthelp.setGeometry(QtCore.QRect(0, 240, 220, 100))
        self.buthelp.setObjectName("buthelp")
        self.buthelp_2 = QtWidgets.QPushButton(self.frame)
        self.buthelp_2.setGeometry(QtCore.QRect(0, 140, 220, 100))
        self.buthelp_2.setObjectName("buthelp_2")
        self.main.addWidget(self.widget1)
        self.main.setStretch(0, 60)
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(1)
        self.Buttonc.clicked.connect(self.inin.clear)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)
        mainWindow.setTabOrder(self.but_2, self.but)
        mainWindow.setTabOrder(self.but, self.inin)
        mainWindow.setTabOrder(self.inin, self.tabWidget_2)
        mainWindow.setTabOrder(self.tabWidget_2, self.label_ans_his)
        mainWindow.setTabOrder(self.label_ans_his, self.Button7)
        mainWindow.setTabOrder(self.Button7, self.buthelp)
        mainWindow.setTabOrder(self.buthelp, self.tabWidget)
        mainWindow.setTabOrder(self.tabWidget, self.Buttonback)
        mainWindow.setTabOrder(self.Buttonback, self.butmain)
        mainWindow.setTabOrder(self.butmain, self.pc_close)
        mainWindow.setTabOrder(self.pc_close, self.Button4)
        mainWindow.setTabOrder(self.Button4, self.Button1)
        mainWindow.setTabOrder(self.Button1, self.Buttonl)
        mainWindow.setTabOrder(self.Buttonl, self.Button8)
        mainWindow.setTabOrder(self.Button8, self.Button2)
        mainWindow.setTabOrder(self.Button2, self.Button5)
        mainWindow.setTabOrder(self.Button5, self.Button0)
        mainWindow.setTabOrder(self.Button0, self.Button9)
        mainWindow.setTabOrder(self.Button9, self.Button3)
        mainWindow.setTabOrder(self.Button3, self.Button6)
        mainWindow.setTabOrder(self.Button6, self.Buttond)
        mainWindow.setTabOrder(self.Buttond, self.Buttonent)
        mainWindow.setTabOrder(self.Buttonent, self.Buttonc)
        mainWindow.setTabOrder(self.Buttonc, self.Buttondd)
        mainWindow.setTabOrder(self.Buttondd, self.Buttoni)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "打码识别"))
        self.label_4.setText(_translate("mainWindow", "###################     打码检测系统"))
        self.pc_close.setText(_translate("mainWindow", "关闭系统"))
        self.label_time.setText(_translate("mainWindow", "0000-00-00 00:00:00"))
        self.label_2.setText(_translate("mainWindow", "V2.3"))
        self.label_3.setText(_translate("mainWindow", "相机状态"))
        self.label_1.setText(_translate("mainWindow", "检测结果"))
        self.but.setText(_translate("mainWindow", "手动检测"))
        self.label_ans_his.setPlaceholderText(_translate("mainWindow", "检测记录:"))
        self.label_13.setText(_translate("mainWindow", "状态输出:"))
        self.label_14.setText(_translate("mainWindow", "PLC通讯:"))
        self.label_16.setText(_translate("mainWindow", "使能"))
        self.label_18.setText(_translate("mainWindow", "触发检测"))
        self.label_27.setText(_translate("mainWindow", "电源"))
        self.label_28.setText(_translate("mainWindow", "严重错误"))
        self.label_31.setText(_translate("mainWindow", "准备检测"))
        self.label_21.setText(_translate("mainWindow", "报警清除"))
        self.label_30.setText(_translate("mainWindow", "报警信息:"))
        self.label_bad_str.setText(_translate("mainWindow", "等待模型初始化"))
        self.label_32.setText(_translate("mainWindow", "检测结果输出:"))
        self.label_15.setText(_translate("mainWindow", "检测时间:"))
        self.label_ans_time.setText(_translate("mainWindow", "0ms"))
        self.label_37.setText(_translate("mainWindow", "结果可信度:"))
        self.label_ans_reliability.setText(_translate("mainWindow", "0"))
        self.label_39.setText(_translate("mainWindow", "检测结果:"))
        self.label_33.setText(_translate("mainWindow", "错误字符数:"))
        self.label_34.setText(_translate("mainWindow", "输出结果:"))
        self.label_ans_bad_num.setText(_translate("mainWindow", "0"))
        self.label_ans_2.setText(_translate("mainWindow", "等待"))
        self.label_35.setText(_translate("mainWindow", "优化建议:"))
        self.label_ans_optimize.setText(_translate("mainWindow", "无"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("mainWindow", "Tab 1"))
        self.Buttonl.setText(_translate("mainWindow", "/"))
        self.Button8.setText(_translate("mainWindow", "8"))
        self.Button7.setText(_translate("mainWindow", "7"))
        self.Buttonent.setText(_translate("mainWindow", "Enter"))
        self.Button1.setText(_translate("mainWindow", "1"))
        self.Buttondd.setText(_translate("mainWindow", ":"))
        self.Button9.setText(_translate("mainWindow", "9"))
        self.Button3.setText(_translate("mainWindow", "3"))
        self.Button4.setText(_translate("mainWindow", "4"))
        self.Button0.setText(_translate("mainWindow", "0"))
        self.Button6.setText(_translate("mainWindow", "6"))
        self.Button2.setText(_translate("mainWindow", "2"))
        self.Buttonback.setText(_translate("mainWindow", "Backspace"))
        self.Button5.setText(_translate("mainWindow", "5"))
        self.Buttoni.setText(_translate("mainWindow", "-"))
        self.Buttond.setText(_translate("mainWindow", "."))
        self.Buttonyear.setText(_translate("mainWindow", "年"))
        self.Buttonmonth.setText(_translate("mainWindow", "月"))
        self.Buttonday.setText(_translate("mainWindow", "日"))
        self.Buttonc.setText(_translate("mainWindow", "C"))
        self.Buttoncn.setText(_translate("mainWindow", "使用\n"
"中文"))
        self.Buttoncn_2.setText(_translate("mainWindow", "使用\n"
"符号"))
        self.inin.setHtml(_translate("mainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton_4.setText(_translate("mainWindow", "+"))
        self.pushButton_5.setText(_translate("mainWindow", "-"))
        self.label_bad.setText(_translate("mainWindow", "0"))
        self.label_bad_2.setText(_translate("mainWindow", "阈值设置"))
        self.label_bad_3.setText(_translate("mainWindow", "当前打码内容"))
        self.label_6.setText(_translate("mainWindow", "图像预处理设置"))
        self.label_10.setText(_translate("mainWindow", "模式:"))
        self.radioButton_hisall.setText(_translate("mainWindow", "全局均衡化"))
        self.radioButton_his.setText(_translate("mainWindow", "灰度归一化"))
        self.radioButton_hisauto.setText(_translate("mainWindow", "自适应均衡化"))
        self.label_17.setText(_translate("mainWindow", "灰度图处理:"))
        self.radioButton_hsv.setText(_translate("mainWindow", "HSV自适应"))
        self.label_12.setText(_translate("mainWindow", "滤波处理:"))
        self.radioButtongauss.setText(_translate("mainWindow", "高斯模糊"))
        self.radioButtonclose.setText(_translate("mainWindow", "膨胀"))
        self.radioButtonopen.setText(_translate("mainWindow", "腐蚀"))
        self.radioButtoneven.setText(_translate("mainWindow", "均值模糊"))
        self.pushButton_open2.setText(_translate("mainWindow", "+"))
        self.pushButton_close1.setText(_translate("mainWindow", "-"))
        self.pushButton_open1.setText(_translate("mainWindow", "-"))
        self.label_open.setText(_translate("mainWindow", "0"))
        self.label_close.setText(_translate("mainWindow", "0"))
        self.pushButton_close2.setText(_translate("mainWindow", "+"))
        self.pushButton_6.setText(_translate("mainWindow", "-"))
        self.label_bad_4.setText(_translate("mainWindow", "95"))
        self.pushButton_7.setText(_translate("mainWindow", "+"))
        self.label_5.setText(_translate("mainWindow", "容错率"))
        self.label_20.setText(_translate("mainWindow", "置信度"))
        self.radioButtonmould.setText(_translate("mainWindow", "模板匹配"))
        self.radioButtongray.setText(_translate("mainWindow", "灰度图"))
        self.radioButtoncolor.setText(_translate("mainWindow", "彩图"))
        self.radioButtonblack.setText(_translate("mainWindow", "黑白图"))
        self.radioButton_otus.setText(_translate("mainWindow", "OTSU"))
        self.radioButton_mean.setText(_translate("mainWindow", "局部均值"))
        self.label_19.setText(_translate("mainWindow", "黑白图处理:"))
        self.radioButton_200.setText(_translate("mainWindow", "颜色提取"))
        self.label_26.setText(_translate("mainWindow", "阈值"))
        self.pushButton_jd1.setText(_translate("mainWindow", "-"))
        self.label_jd.setText(_translate("mainWindow", "99"))
        self.label_lb.setText(_translate("mainWindow", "99"))
        self.pushButton_lb2.setText(_translate("mainWindow", "+"))
        self.pushButton_jd2.setText(_translate("mainWindow", "+"))
        self.label_25.setText(_translate("mainWindow", "精度"))
        self.pushButton_lb1.setText(_translate("mainWindow", "-"))
        self.pushButton_jd1_2.setText(_translate("mainWindow", "-"))
        self.label_jd_2.setText(_translate("mainWindow", "99"))
        self.pushButton_jd2_2.setText(_translate("mainWindow", "+"))
        self.label_41.setText(_translate("mainWindow", "精度"))
        self.pushButton_lb1_2.setText(_translate("mainWindow", "-"))
        self.pushButton_lb2_2.setText(_translate("mainWindow", "+"))
        self.label_lb_2.setText(_translate("mainWindow", "99"))
        self.label_42.setText(_translate("mainWindow", "阈值"))
        self.radioButton_colorhis.setText(_translate("mainWindow", "HSV自适应"))
        self.label_29.setText(_translate("mainWindow", "彩图处理:"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("mainWindow", "Tab 2"))
        self.but_2.setText(_translate("mainWindow", "参数设置"))
        self.label_ans.setText(_translate("mainWindow", "等待"))
        self.but_1.setText(_translate("mainWindow", "输出页面"))
        self.label_9.setText(_translate("mainWindow", "检测结果:"))
        self.but_3.setText(_translate("mainWindow", "报警清除"))
        self.pushButtoncleanlearn.setText(_translate("mainWindow", "清除模板"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("mainWindow", "Tab 1"))
        self.label_7.setText(_translate("mainWindow", "使用说明"))
        self.label_8.setText(_translate("mainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; font-size:22pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">1:软件首次运行需要加载模型(2-10秒)，因此推荐开机以后手动进行2-5次检测(很有必要)</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:18pt;\"><br /></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">2:检测流程示例说明</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">  预处理图像:读取摄像头&gt;预处理图像&gt;图像储存等待调用</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">  检测并判断:收到信号&gt;二次处理图像&gt;检测&gt;对比结果&gt;发出信号&gt;处理图像&gt;屏幕显示结果</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:16pt; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">3:过多的背景可能会影响检测速度与质量，请调节摄像头，尽可能去除多余背景，仅保留检测对象(大幅提升速度)</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:16pt; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">4:程序预设10种图像预处理方法</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">  彩图:  </span><span style=\" font-size:18pt;\">HSV自适应均衡化(加强对比度)</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">  灰度图:  直方图归一化(普通模式)  自适应直方图均衡化(去除光照影响)  全局直方图均衡化(需要滤波)  HSV自适应均衡化(深色背景使用)</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">  黑白图:  OTSU(自动选择全图阈值)  自适应局部均值(备用)  颜色提取(深色背景使用)</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">  降噪:    高斯滤波(降噪)  均值滤波(去除椒盐噪点)  腐蚀(去除白噪点)  膨胀(去除过细的线条) </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:18pt;\"><br /></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">5:字符容错率是允许字符识别出错的个数。特殊符号等导致检测少量时候不准可以视情况设置。</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">   比如:  .与:  /与1  日与8  此时可以设置容错率防止误判。</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">   绝大多数情况此值设0，优先尝试增强图像，更改图像设置。</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">   模板匹配模式不需要此选项，此设置无效。</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:16pt; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">6:置信度是处理完成的图像与预设特征的相似度。</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">   模板匹配模式中则是与存储的模板的相似度。</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">   通过图像处理突出由于各种原因造成的印刷质量问题后由置信度阈值进行判断是否剔除。</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">  </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:16pt; font-weight:600;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("mainWindow", "页"))
        self.label_23.setText(_translate("mainWindow", "推荐设置"))
        self.label_24.setText(_translate("mainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; font-size:18pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">模板匹配预设：    </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    预设：均值自适应+置信度80%    </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    常用：膨胀  腐蚀   开运算</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    特点：传统方案，调试简单，图像处理与黑白图相同，精度可调。</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">灰度图预设: </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    预设1： 置信度95%</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    预设2： 归一化+开运算(腐蚀1次  膨胀1次)+置信度96%</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    常用： 自适应均衡化   膨胀   开运算</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    特点：高速，对印刷质量敏感度较低，过小的缺陷无法检测。</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">黑白图预设:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    预设1： 低精度均值自适应+置信度90-95%</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    预设2： 低精度自适应+开运算(腐蚀1次  膨胀1次)+置信度90%</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    常用：膨胀   开运算</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    特点：精度高，检测精度依靠图片预处理，过高的精度可能造成误判。</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">其他要求：</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    污点会影响黑白图二值化时自适应的阈值，使用黑白图检测时标签需要干净。</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    均匀的光照条件和相机位置才是最重要的，相机注意垂直。</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    适当减少背景(非检测目标)可以大幅提升准确度与提升速度，但是不要太过靠近。</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">*置信度根据实际运行情况设置</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">*光标选择腐蚀为开运算(先腐蚀后膨胀)，选择膨胀为闭运算(先膨胀后腐蚀)，腐蚀与膨胀设置次数为0时不使用。</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">*测试时的检测时间：彩图(35-40ms)  灰度图(30-50ms)   黑白图(35-50ms)   模板匹配(50-60ms)</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("mainWindow", "页"))
        self.butmain.setText(_translate("mainWindow", "检测页面"))
        self.buthelp.setText(_translate("mainWindow", "帮助"))
        self.buthelp_2.setText(_translate("mainWindow", "推荐设置"))
